Various fixes
mxcube/mxcubeqt pull request #241
Opened 2018-06-08 19:52 UTC by MartinSavko

Qt4_matplot_widget
 -- fixing problem with color representation (matplotlib 2.2.2)
 -- account for possibility that sw is a dictionary rather than a list
Qt4_LightControlBrick
 -- accounting for changes in Qt4_MotorSpinBoxBrick it inherits from
Qt4_ProposalBrick2
 -- fix typo
Qt4_data_path_widget
 -- fix problem with incompatible data types
Qt4_TreeBrick
 -- display more detailed information in the status bar if diffractometer hwobj provides it

2018-06-11 07:35 UTC, IvarsKarpics commented
I will test this

2018-06-11 07:47 UTC, IvarsKarpics requested changes

2018-06-11 07:47 UTC, IvarsKarpics commented on BlissFramework/Bricks/Qt4_MotorSpinBoxBrick.py
> +                    Qt4_widget_colors.LIGHT_YELLOW,  # MOVING
This should be as in AbstractMotor. Please revert to previous version and change the state index in you corresponding motor class

2018-06-11 07:47 UTC, IvarsKarpics commented on BlissFramework/Bricks/Qt4_MotorSpinBoxBrick.py
> +        elif hasattr(self.motor_hwobj, 'GUIstep'):
Code block appears twice

2018-06-11 07:47 UTC, IvarsKarpics commented on BlissFramework/Bricks/Qt4_MotorSpinBoxBrick.py
> +                self.limits_changed(self.motor_hwobj.get_limits())
motor_hwobj.update_values should emit all 3 variables. No need to call them again

2018-06-11 07:47 UTC, IvarsKarpics commented on BlissFramework/Bricks/Qt4_TreeBrick.py
> +        logging.getLogger('HWR').info('self.diffractometer_hwobj.get_status() %s' % self.diffractometer_hwobj.get_status())
GenericDiffractometer has no method called get_status. I would suggest not to put log lines in the GUI brick, but use them in the hwobj.

2018-06-11 07:47 UTC, IvarsKarpics commented on BlissFramework/Bricks/Qt4_TreeBrick.py
>          if status:
maybe if `status is None`?

2018-06-12 06:01 UTC, MartinSavko commented on BlissFramework/Bricks/Qt4_TreeBrick.py
>          if status:
While testing I have seen only two values in the status variable in diffractometer_ready_changed: 1 or 0.

2018-06-12 06:01 UTC, MartinSavko commented on BlissFramework/Bricks/Qt4_TreeBrick.py
> +        logging.getLogger('HWR').info('self.diffractometer_hwobj.get_status() %s' % self.diffractometer_hwobj.get_status())
OK.

2018-06-12 06:09 UTC, MartinSavko commented on BlissFramework/Bricks/Qt4_MotorSpinBoxBrick.py
> +                    Qt4_widget_colors.LIGHT_YELLOW,  # MOVING
OK

2018-06-12 06:11 UTC, MartinSavko commented on BlissFramework/Bricks/Qt4_MotorSpinBoxBrick.py
> +        elif hasattr(self.motor_hwobj, 'GUIstep'):
I have reformulated it a bit...

2018-06-12 07:07 UTC, IvarsKarpics requested changes

2018-06-12 07:07 UTC, IvarsKarpics commented on BlissFramework/Bricks/Qt4_TreeBrick.py
>          if status:
Maybe here should be:
```
if status is None:
   try:
       ...
else:
    info_message = status
```

2018-06-12 14:12 UTC, MartinSavko commented on BlissFramework/Bricks/Qt4_MotorSpinBoxBrick.py
> +                self.limits_changed(self.motor_hwobj.get_limits())
I see.

2018-06-12 14:27 UTC, MartinSavko commented on BlissFramework/Bricks/Qt4_TreeBrick.py
>          if status:
The original behavior was that if status could be interpreted as True the info_message was set to "Ready" and to "Not ready" otherwise.

To not alter the previous behavior in case get_status() is not available I would suggest the following formulation 

```python
def diffractometer_ready_changed(self, status):
    self.diffractometer_ready.emit(self.diffractometer_hwobj.is_ready())
    
    try:
        info_message = self.diffractometer_hwobj.get_status()
    except AttributeError:
        info_message = None
        
    if info_message is None and status:
        info_message = "Ready"
        info_status = "ready"
    elif info_message is None:
        info_message = "Not ready"
        info_status = "running"
    
    BlissWidget.set_status_info("diffractometer", info_message, info_status)

```

2018-06-13 07:16 UTC, merged