Sample changer bricks improvements
mxcube/mxcubeqt pull request #242
Opened 2018-06-08 19:58 UTC by MartinSavko

Qt4_CatsSimpleBrick
 -- allow CatsStatusView to inherit from BlissWidget in addition to QGroupBox
 -- improving log messages
Qt4_SampleChangerBrick3
 -- More flexible layout of samples. Redefining mouse vial click events. Not limiting number of samples per basket to 10.

2018-06-11 07:49 UTC, IvarsKarpics requested changes

2018-06-11 07:49 UTC, IvarsKarpics commented on BlissFramework/Bricks/Qt4_CatsSimpleBrick.py
> +        logging.getLogger("HWR").debug("SC StatusView. State changed %s" % str(state))
I am not sure if the gui bricks is the place to print log lines with type HWR?

2018-06-12 05:49 UTC, MartinSavko commented
Indeed Qt4_CatsMaintBrick, Qt4_CatsSimpleBrick are the only ones that do that. 

sed -i 's/logging.getLogger("HWR")/logging.getLogger()/g' Qt4_CatsMaintBrick.py Qt4_CatsSimpleBrick .py

setting to default ...

2018-06-12 07:09 UTC, IvarsKarpics commented
Sorry for counting peanuts, but Qt4_SampleChangerBrick3.py is full with logging lines on each mouse click. Maybe we should introduce even fine grained logging level that could be disabled at the startup.

2018-06-12 13:04 UTC, MartinSavko commented
Removing HWR logger from Qt4_SampleChangerBrick3. Indeed flooding log with every vial click is superfluous -- those messages are at the debug level at the moment.

2018-06-12 13:26 UTC, merged