Cleanup based on pylint
mxcube/mxcubeqt pull request #327
Opened 2019-04-01 08:58 UTC by IvarsKarpics

* Updated gui file (removed references to hwobj in brick where api is used, for example TreeBrick)
* Removed if True: blocks
* Sorted imports
* Converted some come from CamelCase to snake_case

2019-04-01 14:41 UTC, rhfogh commented on gui/GUISupervisor.py
> +                        QtImport.QMessageBox.warning(
Looks like there is an 'eight-spaces' convention behind this. Where does it come from? No objection if there is a standard that says so, but personally I rather prefer the look of the previois version with four spaces less indentation.

2019-04-01 14:46 UTC, rhfogh commented on gui/utils/GUIDisplay.py
> +            def tab_reset_count_slot(self, erase_count,
Are you sure? I tested this in black, and it gave me

            def tab_reset_count_slot(
                self, erase_count, page_index=self.indexOf(scroll_area)
             ):

2019-04-01 14:48 UTC, rhfogh requested changes
OK, apart from my couple of comments

2019-04-02 10:13 UTC, IvarsKarpics commented on gui/GUISupervisor.py
> +                        QtImport.QMessageBox.warning(
Yes indeed it looks strange. It was suggested by running pylint. I will revert back to 4 spaces.

2019-04-02 10:15 UTC, IvarsKarpics commented on gui/utils/GUIDisplay.py
> +            def tab_reset_count_slot(self, erase_count,
I guess that was my manual fix. I changed it to your suggestion.

2019-04-03 14:17 UTC, merged