Fixes suggested by pylint
mxcube/mxcubeqt pull request #341
Opened 2019-04-24 09:13 UTC by IvarsKarpics

Cleaned up base classes and bricks based on pylint:
* removed not used code.
* added missing items to __init__
* removed not used imports
* etc

2019-04-24 12:30 UTC, rhfogh commented on gui/bricks/AttenuatorsBrick.py
> +            self.connect(api.transmission,
This does not look like what black would suggest

2019-04-24 12:31 UTC, rhfogh commented on gui/bricks/AttenuatorsBrick.py
> +                self.new_value_ledit,
Again, are w2e not supposed ot use black formatting?

2019-04-24 12:34 UTC, rhfogh commented on gui/bricks/EMBL/StillCollectionPreviewBrick.py
> +        api.parallel_processing.connect("processingStarted", self.processing_started)
Is api.parallel_processwign always set?

2019-04-24 12:42 UTC, rhfogh commented on gui/bricks/MachineInfoBrick.py
> +            for item in values_list.values():
If vlaues_list is a list is has not values() method; if it is a dictionary is should be renamed.,

2019-04-24 12:43 UTC, rhfogh commented on gui/bricks/MotorSpinBoxBrick.py
> +        self.pos_history = []
Rename to position_history??

2019-04-24 12:50 UTC, rhfogh commented on gui/utils/PropertyBag.py
> +            value = self.properties[property_key].get_value()
Surely that should be 
'value = item.get_value()'

The following would be shorter (unless pylint protests):

    item = self.properties.get(property_key)
    if item is None:
        return None
    else:
        return item.get_value()

Or even shorter (which I would prefer(:

return None if item is None else item.get_value()

2019-04-24 12:53 UTC, rhfogh requested changes
Two general comments:
- maybe run black over all the code?
- When adding :param: documentation, as a minimum put in the data type. I would recommend the syntax from the Python 3 typing package. If all you do is repeat the parameter name it is better to have nothing at all

2019-04-25 08:13 UTC, IvarsKarpics commented on gui/bricks/AttenuatorsBrick.py
> +                self.new_value_ledit,
I will run autopep and black on all changed files.

2019-04-25 08:14 UTC, IvarsKarpics commented on gui/bricks/EMBL/StillCollectionPreviewBrick.py
> +        api.parallel_processing.connect("processingStarted", self.processing_started)
This is EMBL specific brick and I do not see point to add some checks. Later if this brick becomes a core of mxcube, then one can add a if block.

2019-04-25 08:16 UTC, IvarsKarpics commented on gui/bricks/MachineInfoBrick.py
> +            for item in values_list.values():
You are right. I changed it to values_dict

2019-04-25 08:17 UTC, IvarsKarpics commented on gui/bricks/MotorSpinBoxBrick.py
> +        self.pos_history = []
Done

2019-04-25 08:18 UTC, IvarsKarpics commented on gui/utils/PropertyBag.py
> +            value = self.properties[property_key].get_value()
OK, makes sense

2019-04-25 08:49 UTC, rhfogh commented on gui/bricks/EMBL/StillCollectionPreviewBrick.py
> +        api.parallel_processing.connect("processingStarted", self.processing_started)
Cool.

2019-04-25 09:22 UTC, rhfogh approved these changes
Ready to merge when you say so

2019-04-25 09:39 UTC, merged