Added parameter validation to paramsgui and GPhL parameter queries.
mxcube/mxcubeqt pull request #346
Opened 2019-04-30 09:51 UTC by rhfogh

Added parameter validation to GPhL using paramsgui for runtime parameter queries. 

NB goes with matching PR in HardwareRepository

2019-04-30 10:00 UTC, IvarsKarpics commented
Just a minor pylint suggestions: https://app.codacy.com/app/mxcube/mxcube/pullRequest?prid=3513574
Otherwise I am fine with the PR.

2019-04-30 10:28 UTC, rhfogh commented
@IvarsKarpics I am weorking on fixing the Codacy problems. Till soon, Rasmus

2019-04-30 12:24 UTC, rhfogh commented
Added pylint/black fixes

2019-04-30 13:43 UTC, IvarsKarpics requested changes

2019-04-30 13:43 UTC, IvarsKarpics commented on gui/utils/paramsgui.py
> +        policy.setVerData(QtImport.QSizePolicy.Fixed)
There is no setVerData in Qt5. Instead please use setVerticalPolicy: https://doc.qt.io/qt-5/qsizepolicy.html

2019-04-30 13:52 UTC, rhfogh commented on gui/utils/paramsgui.py
> +        policy.setVerData(QtImport.QSizePolicy.Fixed)
Fixed and pushed

2019-04-30 13:52 UTC, rhfogh commented on gui/utils/paramsgui.py
> +        policy.setVerData(QtImport.QSizePolicy.Fixed)
Thanks for checking.

2019-05-02 06:55 UTC, IvarsKarpics approved these changes

2019-05-02 06:55 UTC, merged