CameraBrick: QActionGroup for an exclusive selection on image scale menu
mxcube/mxcubeqt pull request #374
Opened 2020-02-10 15:42 UTC by natxo14

Add QActionGroup to QtImport
Use it for a mutual exclusive menu when selecting scale on the right-click menu ( now, user can select several checkboxes at the same time )

2020-02-10 16:42 UTC, IvarsKarpics commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Clones removed
==============
+ gui/bricks/CameraBrick.py  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/mxcube/mxcube/pullRequest?prid=4976931&bid=16439464)

2020-02-11 10:26 UTC, IvarsKarpics requested changes

2020-02-11 10:26 UTC, IvarsKarpics commented on gui/bricks/CameraBrick.py
> +                self.graphics_view.resize(700,700)
It would be good to define the size via property instead of hard coded values.

2020-02-11 10:28 UTC, natxo14 commented on gui/bricks/CameraBrick.py
> +                self.graphics_view.resize(700,700)
Completely agree.
I was making some tests on widget's size and how it changed the global rendering of the app; I forgot to change that. I'll fix it soon.
Thanks!

2020-02-18 10:44 UTC, natxo14 commented on gui/bricks/CameraBrick.py
> +                self.graphics_view.resize(700,700)
Finally I removed the 'resize()' call: 
on my experience with Qt, is better to rely on Qt's layout management unless we're looking for a very precise sizing of widget's inserted in layouts.

2020-02-18 10:45 UTC, IvarsKarpics commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Clones removed
==============
+ gui/bricks/CameraBrick.py  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/mxcube/mxcube/pullRequest?prid=4976931&bid=16439464)

2020-02-18 10:59 UTC, merged