Bug fixes to run mxcube with latest HWR
mxcube/mxcubeqt pull request #402
Opened 2020-09-14 08:51 UTC by IvarsKarpics

2020-09-15 13:06 UTC, rhfogh commented on gui/bricks/MotorSpinBoxBrick.py
> +        if limits and not (None in limits or float('nan') in limits):
This will not work - float('nan') == float('nan') evaluates to False

You will have to do

if limits and not(None in limits or any(math.isnan(x) for x in limits)):

2020-09-15 13:07 UTC, rhfogh commented on gui/bricks/MotorSpinBoxBrick.py
> +        if not new_position in (None, float('nan'), float('inf')):
Again, you need to use math,isnan insted of comaring with NaN

2020-09-15 13:10 UTC, rhfogh commented on gui/widgets/create_task_base.py
> +        print("create ", free_pin_mode, sample_is_mounted, shape)
Do you want to keep this in?

2020-09-15 13:12 UTC, rhfogh requested changes
Thanks!

Once the NaN stuff is fixed this should be merged.

2020-10-13 17:55 UTC, IvarsKarpics commented on gui/bricks/MotorSpinBoxBrick.py
> +        if limits and not (None in limits or float('nan') in limits):
done

2020-10-13 17:57 UTC, IvarsKarpics commented on gui/widgets/create_task_base.py
> +        print("create ", free_pin_mode, sample_is_mounted, shape)
no

2020-10-13 20:48 UTC, beteva commented on gui/bricks/EnergyBrick.py
> +        self.connect(HWR.beamline.energy, "energyChanged", self.energy_changed)
This should better be valueChanged, although for time being we still have energyChanged. What emits the statusInfoChanged, deviceReady and deviceNotReady?

2020-10-13 20:55 UTC, beteva commented on gui/bricks/TreeBrick.py
>                  HWR.beamline.safety_shutter, "shutterStateChanged", self.shutter_state_changed
Should be rather stateChanged, both here and in specific HO, although one finds shutterStateChanged in some HO.

2020-10-14 07:37 UTC, IvarsKarpics commented on gui/bricks/EnergyBrick.py
> +        self.connect(HWR.beamline.energy, "energyChanged", self.energy_changed)
Ok, I will fix this

2020-10-15 08:21 UTC, IvarsKarpics commented
@beteva  and @rhfogh  are you ok with the PR?

2020-10-15 08:26 UTC, rhfogh commented on gui/bricks/EnergyBrick.py
> +        print(energy_value)
Remove this one?

2020-10-15 08:31 UTC, IvarsKarpics commented on gui/bricks/EnergyBrick.py
> +        print(energy_value)
done

2020-10-15 08:31 UTC, rhfogh commented on gui/utils/QtImport.py
> +            #self.setValue(self.value())
Looks like it might be necessary - but OK, if you say it is not.

2020-10-15 08:35 UTC, rhfogh commented on gui/widgets/acquisition_still_widget.py
> +    def update_energy(self, energy):
update_energy and set_energy really ought to be changd to take only one parameter. Anyway, wav seems to be unused. This may not be the place, but is there any known reason why this should not be done (elsewhere)?

2020-10-15 08:36 UTC, rhfogh commented on gui/widgets/create_advanced_widget.py
> +        except:
Should that be 'Except Ecxception', so as not to block keyboard interrupts?

2020-10-15 08:40 UTC, rhfogh commented on gui/widgets/create_task_base.py
> +                acq_widget.update_energy(energy)
Here teh wavelength parameter is being romoved. Good. Did I misunderstand something or is it being added elsewhere?

2020-10-15 08:40 UTC, rhfogh approved these changes
The sooner this is merged, the better.

2020-10-15 08:53 UTC, beteva approved these changes
@IvarsKarpics I approve this PR. There are things to be changes in the future to be compliant with the new HWR, but I guess it is a long term effort.

2020-10-15 08:53 UTC, beteva commented on gui/bricks/ApertureBrick.py
> +                HWR.beamline.beam.aperture, "diameterIndexChanged", self.diameter_changed
I thought AbstractAperture was one of the deprecated HO. Do you really need this signal or valueChanged is enough?

2020-10-15 08:53 UTC, beteva commented on gui/bricks/ApertureBrick.py
>          )
Depending on AbstractAperture and moreover MD2 implementation only. OK for now, but probably irrelevant in the future.

2020-10-15 08:53 UTC, beteva commented on gui/bricks/ApertureBrick.py
> +        HWR.beamline.beam.aperture.set_position(self.aperture_position_combo.currentIndex())
See the above AbstractAperture comment.

2020-10-15 08:53 UTC, beteva commented on gui/bricks/MotorSpinBoxBrick.py
> +            #limits = self.make_limits_bounded(limits)
You are probably missing isinf as well.

2020-10-15 08:53 UTC, beteva commented on gui/bricks/TaskToolBoxBrick.py
> +
linting not done ;-)

2020-10-15 08:53 UTC, beteva commented on gui/bricks/TreeBrick.py
>                  HWR.beamline.safety_shutter, "shutterStateChanged", self.shutter_state_changed
Still using hutterStateChanged ?

2020-10-15 08:53 UTC, beteva commented on gui/bricks/TreeBrick.py
> +        is_open = bool(state and state.lower().startswith('open'))
The states now should be OPEN, CLOSED, UNKNOWN and whatever else you have in you specific shutter implementation. Also the state is an Enum, not a string. This is probably OK, but it does not correspond to the new HWR.

2020-10-15 10:18 UTC, IvarsKarpics commented on gui/widgets/create_advanced_widget.py
> +        except:
True. I also changed BaseException to Exception

2020-10-15 10:20 UTC, IvarsKarpics commented on gui/widgets/create_task_base.py
> +                acq_widget.update_energy(energy)
It was never used: there is no wavelength edit in the create_task* widgets. There is no problem to add it when the need comes up.

2020-10-15 10:22 UTC, IvarsKarpics commented on gui/bricks/MotorSpinBoxBrick.py
> +            #limits = self.make_limits_bounded(limits)
I guess limit could be inf. Or not?

2020-10-15 10:22 UTC, merged

2020-10-15 10:22 UTC, IvarsKarpics commented on gui/bricks/TreeBrick.py
> +        is_open = bool(state and state.lower().startswith('open'))
fixed

2020-10-15 10:23 UTC, rhfogh commented on gui/bricks/MotorSpinBoxBrick.py
> +            #limits = self.make_limits_bounded(limits)
Good point - in principle it could

2020-10-15 10:24 UTC, rhfogh commented
@IvarsKarpics 
Ah, ws I just too quick, merging? Do you want me to unmerge?Or wait while you make another touch-up one?

2020-10-15 10:26 UTC, IvarsKarpics commented
Its fine. I will open an another PR after the rework_re_emit_values PR in HWR has been accepted.

2020-10-15 11:59 UTC, beteva commented on gui/bricks/TreeBrick.py
> +        is_open = bool(state and state.lower().startswith('open'))
BTW, we are talking states, but effectively with the new HWR these are values. The states are the ones, defined in the BaseHardwareObject, and represent the execution state.