WIP Hwr repository rename
mxcube/mxcubeqt pull request #415
Opened 2020-12-17 17:17 UTC by rhfogh

Renamed HardwareRepository and HardwareObjects

Goes together with HardwareObjects PR #605 - see there for comments and details

2020-12-18 17:53 UTC, IvarsKarpics requested changes

2020-12-18 17:53 UTC, IvarsKarpics commented on gui/BaseComponents.py
> +from mx3core import HardwareRepository as HWR
I guess this is not the final name of the repository? To be inline with #417 it should be mxcubecore

2020-12-18 18:49 UTC, rhfogh commented on gui/BaseComponents.py
> +from mx3core import HardwareRepository as HWR
Indeed. As it says in the comments to #605, 'mx3core' is just a placeholder for now. We can change it to anything we want by a single global replace command.

2021-01-27 16:38 UTC, rhfogh commented
OK, I have now renamed all occurrences of 'mx3core' to 'mxcubecore', in parallel with changes to HardwareObjects PR #605.
This ought to be what we want to carry on from.

2021-03-03 11:19 UTC, merged