Update repository name in documentation
mxcube/mxcubeqt pull request #429
Opened 2021-06-16 09:58 UTC by IvarsKarpics

2021-06-16 10:10 UTC, jordiandreu requested changes

2021-06-16 10:10 UTC, jordiandreu commented on docs/how_to_create_qt_brick.md
> +- Before creating and submiting a new brick to the git repository, please inspect [mxcubeqt/bricks](https://github.com/mxcubeqt/mxcuebqt/tree/master/bricks) directory if there is a brick that might f
The url is not correct here

2021-06-16 10:10 UTC, jordiandreu commented on README.md
>  [![Build Status](https://travis-ci.org/mxcube/mxcube.svg?branch=master)](https://travis-ci.org/mxcube/mxcube)
Is the badge url correct?

2021-06-16 10:10 UTC, jordiandreu commented on docs/how_to_run_mxcube_qt.md
I think this should be reviewed at some point, at least for the mockups. Maybe we can add a TODO here?

2021-06-16 10:42 UTC, rhfogh commented on docs/how_to_create_hwobj.md
> +  - def **init**(self)
Missing the underscores?

2021-06-16 10:42 UTC, rhfogh commented on docs/how_to_create_hwobj.md
> +  - def **init**(self)
Will this get teh right indentation?

2021-06-16 10:45 UTC, rhfogh approved these changes
Just a quick look, but looks good

2021-06-18 07:35 UTC, IvarsKarpics commented on docs/how_to_create_qt_brick.md
> +- Before creating and submiting a new brick to the git repository, please inspect [mxcubeqt/bricks](https://github.com/mxcubeqt/mxcuebqt/tree/master/bricks) directory if there is a brick that might f
fixed

2021-06-18 07:37 UTC, IvarsKarpics commented on README.md
>  [![Build Status](https://travis-ci.org/mxcube/mxcube.svg?branch=master)](https://travis-ci.org/mxcube/mxcube)
I removed the badge because travis moved to travis-ci.com and apparently is not available for public projects and one has to pay. We should discuss this issue in F2F meeting.

2021-06-18 07:38 UTC, IvarsKarpics commented on docs/how_to_create_hwobj.md
> +  - def **init**(self)
Pycharm did some strange corrections. Now it should be fine

2021-06-22 09:02 UTC, IvarsKarpics commented
Is the PR ok? Can someone merge it?

2021-06-22 10:52 UTC, jordiandreu approved these changes

2021-06-22 10:53 UTC, jordiandreu commented
Thanks for the work! Merged!

2021-06-22 10:53 UTC, merged