P11 mxcubeqt bricks update
mxcube/mxcubeqt pull request #447
Opened 2023-08-29 13:57 UTC by agruzinov

Here is cumulative update from P11 with updates together from Bixente.

Cheers,
Andrey

2023-08-29 17:38 UTC, rhfogh commented
Dear Andrey,
Would you mind dealing with my PR first? There is probably not that much overlap, which should make it relatively easy, but I did put mine in first, a month ago. If we merge yours in first, then I shall have to rebase my PR on yours . It would be nice (for me at least ;-) ) if we could merge mine first, and then rebase yours on the new tip.

2023-08-30 10:45 UTC, rhfogh commented on mxcubeqt.egg-info/PKG-INFO
> +Metadata-Version: 2.1
For my information - should this be checked in at all, and why? I honestly do not know.

2023-08-30 10:47 UTC, rhfogh commented on mxcubeqt.egg-info/requires.txt
> +PyQt5==5.14
We need to regularise our licensing situation here, but it need nto hold up your PR. 
Also we need to test our version checking mechanism If it worked like it should (see utils/qt_import SUPPORTED_VERSIONS) then this version of PyQt5 should trigger an error.

2023-08-30 10:56 UTC, rhfogh commented on mxcubeqt/bricks/desy/p11_deice_brick.py
> +            dev_class = sClass
This may fail, since sClass may not be set if there is an error in the line setting it.
If you aer sure it will never fail, you should define sClass before you start the try: statement. If not you need another fallback for the case when sClass cannot be set.

2023-08-30 10:57 UTC, rhfogh commented on mxcubeqt/bricks/desy/p11_deice_brick.py
> +        dict = self.__dict__.copy()
Better to use another variable name - 'dicvt' is a system keyword.

2023-08-30 11:55 UTC, rhfogh commented on mxcubeqt/bricks/desy/p11_deice_brick.py
> +            state = self.state_dict[state]
If self.dev.stagte gives an error, 'state' will not be defined, and this line will fail. A different failuer4e handling mechanism is needed.

2023-08-30 12:01 UTC, rhfogh commented on mxcubeqt/bricks/desy/value_state_brick.py
> +    def setToolTip(self, name=None, state=None):
Function seems wrong. 'tip' is not initialised, and state, states, and name iare not used.

2023-08-30 12:06 UTC, rhfogh commented on mxcubeqt/bricks/multi_state_brick.py
> +    def fill_positions(self, positions=None):
Why the 'positions' parameter since ti is not used. To absorb parameters generated by a signal?

2023-08-30 12:16 UTC, rhfogh requested changes
Pretty good. This is all I have (apart from handing PR #448 and rebasing onto develop tip)

2023-08-30 14:40 UTC, agruzinov commented on mxcubeqt.egg-info/PKG-INFO
> +Metadata-Version: 2.1
Actually those files (in egg-info) have been modified automatically, or at least not intentionally. Maybe it is better to add them to the gitignore?

2023-08-30 14:40 UTC, agruzinov commented on mxcubeqt.egg-info/PKG-INFO
> +Metadata-Version: 2.1
Maybe I should drop this commit for now.

2023-08-30 14:50 UTC, agruzinov commented
OK, rebasing is done, so should be fine now.

2023-08-30 14:52 UTC, agruzinov commented
p11_deice_brick is not used at the moment and was used as an example attempt. Added for safekeeping. Actually the deicing should be implemented probably without building another brick.

2023-08-30 14:57 UTC, agruzinov commented on mxcubeqt/bricks/desy/value_state_brick.py
> +    def setToolTip(self, name=None, state=None):
Value_state brick is also currently WIP and was started by Bixente. Thanks for looking into it anyway. It needs to be progressed as soon as the rest will be debugged.

2023-08-30 15:18 UTC, rhfogh commented on mxcubeqt.egg-info/PKG-INFO
> +Metadata-Version: 2.1
I do nto think this should be checked in, in fact.

2023-08-30 15:21 UTC, rhfogh commented on mxcubeqt/bricks/p11_simple_brick.py
> +#
With a name like  p11_simple_brick, should this maybe be in the desy directory?

2023-08-30 15:53 UTC, rhfogh commented
There is something really weird here.

When I look at the file differences, there are a lot of differences for e.g. create_gphl_workflow_widget and jsonparamsgui, files that were changed on my side before rebasing and that should *not* be changing again. Yet, when I look at mxcubeqt/develop, those changes (that your PR is supposedly introducing) ar already there. And when I look at the branches fetched down to my local computer, again those files are identical (and correct) in both your branch and the develop branch.

Sorry for the complication, but would you mind closing down this PR and making a new one between the same branches? Something must have gone slightly wrong either in rebasing or on github, and if possible I would rather not introduce confusion in the commits.

2023-08-30 17:00 UTC, agruzinov commented on mxcubeqt/bricks/p11_simple_brick.py
> +#
Yes! Slipped through the cracks.

2023-08-30 17:03 UTC, agruzinov commented
First rebase seems not processed properly. New rebase needed. Closing.

2023-08-30 17:03 UTC, closed without merging