P11 qt develop 2
mxcube/mxcubeqt pull request #457
Opened 2023-12-02 15:03 UTC by agruzinov

Another round of update to the latest develop. Main add is in confirm_dilalog.py to show N/A in case some of the acquisition parameters are not properly initialized. It helped to track the bug in core in Beamline.py where osc_start was initialized almost always to the "None" because in the beamline_config.yml osc_start was set to 0.0. Changing it to the 0.001 was fixing the problem.

This has also fixed the "red" None value bnox for osc_start in Characterization tab.

BeamSize display was added by Bixente.

2024-02-29 12:57 UTC, rhfogh commented on mxcubeqt/bricks/multi_state_brick.py
> +        unit = self.multi_hwobj.get_properties_(posidx, "unit")
I think get_properties has to be refactored.
First it returns either a value or a dictionary or NOne - too confusing. 
Second the code using it clearly assumes you always get a value
Then the name suggests it is a variant of get_properties, which is not really teh case
Then it is a plural name with a singular return value

2024-02-29 13:43 UTC, rhfogh commented on mxcubeqt/gui_supervisor.py
> +    from ruamel.yaml import YAML
This won't work. If you do not set YAML, the code that uses it below will break anyway. Can't we just say that ruamel.yaml is a requirement and do a single line of 'from ruamel.yaml import YAML'? If not this would need to be more complex

2024-02-29 13:44 UTC, rhfogh commented on mxcubeqt/utils/jsonparamsgui.py_backup
> +#
This should not be checked in. we have the repository for backup, so this kind of file, while suseful, should stay on your computer.

2024-02-29 13:47 UTC, rhfogh commented on mxcubeqt/widgets/create_advanced_widget.py
> +                    "%.2f" % float(0)
Why this?

2024-02-29 13:50 UTC, rhfogh commented
What is the problem exactly with the red boxes? 

I found a bug in Beamline.py that changed osc_start form 0.0 to None - I shall put in a fix for that ASAP. Might that solve some of these problems??

2024-02-29 13:50 UTC, rhfogh requested changes
See comments

2024-03-01 12:28 UTC, agruzinov commented on mxcubeqt/utils/jsonparamsgui.py_backup
> +#
My bad, was too fast, thanks!

2024-03-01 12:29 UTC, agruzinov commented on mxcubeqt/widgets/create_advanced_widget.py
> +                    "%.2f" % float(0)
I've tried on python 3.11.2, and apparently there explicit casting to int is removed. There are for sure other places but this one I've found so far.

2024-03-01 12:30 UTC, agruzinov commented
I guess it is the same bug in the Beamline.py This might be it.

2024-03-01 14:00 UTC, rhfogh commented on mxcubeqt/widgets/create_advanced_widget.py
> +                    "%.2f" % float(0)
My question was rather why you wanted the default to be zero rather than the current position. In that context I am not sure I understand your answer.

2024-03-04 15:41 UTC, agruzinov commented on mxcubeqt/bricks/multi_state_brick.py
> +        unit = self.multi_hwobj.get_properties_(posidx, "unit")
Added changes into #459

2024-03-04 15:41 UTC, agruzinov commented on mxcubeqt/gui_supervisor.py
> +    from ruamel.yaml import YAML
changed in #459

2024-03-04 15:46 UTC, agruzinov commented on mxcubeqt/widgets/create_advanced_widget.py
> +                    "%.2f" % float(0)
Sorry, I've misunderstood it. This was set to quickly remove the error messages due to the fact that the we do not have kappa snd phi and they are set to None. 

I was not very successful to disentangle centring that is happening in the P11Nanodiff.py and "other" centring from the qt part due to limited beamline access. Do you have any comment on how to set it up properly? It looks like that the values are all none in this case and this breaks setting of the grid for example.

2024-03-04 15:48 UTC, agruzinov commented
Red boxes are fixed after merging of mxcubecore:#861 indeed, so after all I've started another more cleaner PR #459.

2024-05-27 14:08 UTC, closed without merging

2024-05-27 14:08 UTC, agruzinov commented
Substituted by PR#459. Closing.